# Generated by Django 4.1.7 on 2023-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(default='', max_length=100)),
                ('rus_name', models.CharField(default='', max_length=100)),
                ('dir', models.CharField(blank=True, max_length=250, null=True)),
                ('issue_year', models.PositiveSmallIntegerField(null=True)),
                ('avg_rating', models.FloatField(blank=True, default=0.0)),
                ('admin_rating', models.FloatField(blank=True, default=0.0)),
                ('type', models.CharField(max_length=100)),
                ('poster', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chapters_quantity', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('genre', models.ManyToManyField(to='manga.genre')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манги',
            },
        ),
    ]
