version: "3"

services:
  db:
    image: postgres:12.1
    container_name: manga_db
    hostname: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manga_service
    restart: always
    env_file:
      - .env
    ports:
      - "8123:8123"
    volumes:
      - .:/MangoRead
      - ./static:/static
    depends_on:
      - db
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
      --no-input && gunicorn -b 0.0.0.0:8123 heart.wsgi --reload"

volumes:
  postgres_data:
