version: "3"

services:
  manga_db:
    image: postgres:latest
    container_name: manga_db
    hostname: manga_db
    environment:
      POSTGRES_DB: manga_db
      POSTGRES_USER: tuser
      POSTGRES_PASSWORD: ubuntu
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    container_name: manga_cont
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && 
      python manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8123 MangaRead.wsgi --reload"
    env_file:
      - .env
    volumes:
      - .:/MangaRead
      - ./static:/static
    ports:
      - "8123:8123"
    depends_on:
      - manga_db

volumes:
  postgres_data:
